import environ

from .base import *


env = environ.Env(
    DEBUG = (bool, False)
)

SECRET_KEY = env("SECRET_KEY")

DEBUG = env('DEBUG')

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

DATABASES = {
    "default": env.db()
}

AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')

AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')

AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')

AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN')

AWS_S3_OBJECT_PARAMETERS = env('AWS_S3_OBJECT_PARAMETERS')

AWS_LOCATION = env('AWS_LOCATION')

STATIC_URL = env('STATIC_URL')

STATICFILES_STORAGE = env('STATICFILES_STORAGE')
