# Generated by Django 3.1.5 on 2021-02-05 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_livro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_pub',
            field=models.DateField(default=datetime.date),
        ),
    ]
