# Generated by Django 4.1.4 on 2022-12-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
